/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package administrasi;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Candra
 */
public class adminFrame extends javax.swing.JFrame {
    
    KoneksiDB k = new KoneksiDB();
    int hari, bulan, tahun;
    String strBulan, tanggal;
    Color f=new Color(0,0,0);
    Color d=new Color(231,0,0);
    Color e=new Color(255,255,255);
    String a;
    String file="/images/bc3.jpg";

  
    public class Background extends JPanel {
    
    private Image img;
    public Background(String file){
        img = new ImageIcon(getClass().getResource(file)).getImage();
        
    }
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D gd = (Graphics2D) g.create();
        gd.drawImage(img, 0, 0, getWidth(), getHeight(), null);
        gd.dispose();
    }
}
    public String kodek3, hak3,nama;
    public adminFrame(String kodek5, String hak5) {
        kodek3 = kodek5;
        hak3 = hak5;
        k.query = "select Nama_Karyawan from karyawan  where Kode_Karyawan ='"+kodek3+"'";
         k.getData();
         
        try {
            while(k.rs.next()){
                nama =k.rs.getString("Nama_Karyawan");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "info", JOptionPane.INFORMATION_MESSAGE);
        }
        initComponents();
        setDateTime();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton6 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bt_petugas1 = new javax.swing.JButton();
        bt_pelanggan1 = new javax.swing.JButton();
        bt_transaksi1 = new javax.swing.JButton();
        bt_barang1 = new javax.swing.JButton();
        bt_laporan1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        panelisi1 = new Background(file);
        karyawan_null1 = new javax.swing.JLabel();
        icon_karyawan1 = new javax.swing.JLabel();
        pelanggan_null1 = new javax.swing.JLabel();
        icon_pelanggan1 = new javax.swing.JLabel();
        barang_null1 = new javax.swing.JLabel();
        icon_barang1 = new javax.swing.JLabel();
        transaksi_null1 = new javax.swing.JLabel();
        icon_transaksi1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lb_date1 = new javax.swing.JLabel();
        lb_time1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bt_petugas = new javax.swing.JButton();
        bt_pelanggan = new javax.swing.JButton();
        bt_transaksi = new javax.swing.JButton();
        bt_barang = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lb_nama = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        lb_hak = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        panelisi = new Background(file);
        karyawan_null = new javax.swing.JLabel();
        icon_karyawan = new javax.swing.JLabel();
        pelanggan_null = new javax.swing.JLabel();
        icon_pelanggan = new javax.swing.JLabel();
        barang_null = new javax.swing.JLabel();
        icon_barang = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lb_date = new javax.swing.JLabel();
        lb_time = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jButton6.setText("jButton6");

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(231, 0, 0));

        bt_petugas1.setBackground(new java.awt.Color(255, 255, 255));
        bt_petugas1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_petugas1.setText("Karyawan");
        bt_petugas1.setBorder(null);
        bt_petugas1.setBorderPainted(false);
        bt_petugas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_petugas1.setFocusPainted(false);
        bt_petugas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_petugas1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_petugas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_petugas1MouseExited(evt);
            }
        });
        bt_petugas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_petugas1ActionPerformed(evt);
            }
        });

        bt_pelanggan1.setBackground(new java.awt.Color(255, 255, 255));
        bt_pelanggan1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_pelanggan1.setText("Pelanggan");
        bt_pelanggan1.setBorder(null);
        bt_pelanggan1.setBorderPainted(false);
        bt_pelanggan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_pelanggan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_pelanggan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_pelanggan1MouseExited(evt);
            }
        });
        bt_pelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pelanggan1ActionPerformed(evt);
            }
        });

        bt_transaksi1.setBackground(new java.awt.Color(255, 255, 255));
        bt_transaksi1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_transaksi1.setText("Transaksi");
        bt_transaksi1.setBorder(null);
        bt_transaksi1.setBorderPainted(false);
        bt_transaksi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_transaksi1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_transaksi1MouseExited(evt);
            }
        });
        bt_transaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transaksi1ActionPerformed(evt);
            }
        });

        bt_barang1.setBackground(new java.awt.Color(255, 255, 255));
        bt_barang1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_barang1.setText("Barang");
        bt_barang1.setBorder(null);
        bt_barang1.setBorderPainted(false);
        bt_barang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_barang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_barang1MouseExited(evt);
            }
        });
        bt_barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_barang1ActionPerformed(evt);
            }
        });

        bt_laporan1.setBackground(new java.awt.Color(255, 255, 255));
        bt_laporan1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_laporan1.setText("Laporan");
        bt_laporan1.setBorder(null);
        bt_laporan1.setBorderPainted(false);
        bt_laporan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_laporan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_laporan1MouseExited(evt);
            }
        });
        bt_laporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_laporan1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("New York");

        jLabel2.setText("jLabel1");

        jButton2.setText("Logout");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_petugas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_barang1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_laporan1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_transaksi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_pelanggan1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGap(92, 92, 92)
                .addComponent(bt_petugas1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_pelanggan1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(bt_transaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_barang1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_laporan1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel18)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelisi1.setBackground(new java.awt.Color(255, 255, 255));

        karyawan_null1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        karyawan_null1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        karyawan_null1.setText("null");

        icon_karyawan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/karyawan.png"))); // NOI18N

        pelanggan_null1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        pelanggan_null1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pelanggan_null1.setText("null");

        icon_pelanggan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pelanggan.png"))); // NOI18N

        barang_null1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        barang_null1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barang_null1.setText("null");

        icon_barang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barang.png"))); // NOI18N

        transaksi_null1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        transaksi_null1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transaksi_null1.setText("null");

        icon_transaksi1.setBackground(new java.awt.Color(204, 204, 204));
        icon_transaksi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transaksi.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("null");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laporan.png"))); // NOI18N

        javax.swing.GroupLayout panelisi1Layout = new javax.swing.GroupLayout(panelisi1);
        panelisi1.setLayout(panelisi1Layout);
        panelisi1Layout.setHorizontalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelisi1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_barang1)
                .addGap(74, 74, 74)
                .addComponent(icon_pelanggan1)
                .addGap(74, 74, 74)
                .addComponent(icon_karyawan1)
                .addGap(74, 74, 74)
                .addComponent(icon_transaksi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(32, 32, 32))
            .addGroup(panelisi1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(barang_null1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(pelanggan_null1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(karyawan_null1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(transaksi_null1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panelisi1Layout.setVerticalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelisi1Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelisi1Layout.createSequentialGroup()
                        .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon_barang1)
                            .addComponent(icon_pelanggan1)
                            .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(icon_transaksi1)
                                .addComponent(icon_karyawan1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(karyawan_null1)
                            .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pelanggan_null1)
                                .addComponent(transaksi_null1)
                                .addComponent(jLabel12))
                            .addComponent(barang_null1))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelisi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelisi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        lb_date1.setBackground(new java.awt.Color(0, 255, 204));
        lb_date1.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        lb_date1.setForeground(new java.awt.Color(255, 255, 255));
        lb_date1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_date1.setText("07 February 2020 ");

        lb_time1.setBackground(new java.awt.Color(0, 255, 204));
        lb_time1.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        lb_time1.setForeground(new java.awt.Color(255, 255, 255));
        lb_time1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_time1.setText("07.50.00 PM");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lb_date1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(302, 302, 302)
                .addComponent(lb_time1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_time1)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(231, 0, 0));

        bt_petugas.setBackground(new java.awt.Color(255, 255, 255));
        bt_petugas.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_petugas.setText("Karyawan");
        bt_petugas.setBorder(null);
        bt_petugas.setBorderPainted(false);
        bt_petugas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_petugas.setFocusPainted(false);
        bt_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_petugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_petugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_petugasMouseExited(evt);
            }
        });
        bt_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_petugasActionPerformed(evt);
            }
        });

        bt_pelanggan.setBackground(new java.awt.Color(255, 255, 255));
        bt_pelanggan.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_pelanggan.setText("Pelanggan");
        bt_pelanggan.setBorder(null);
        bt_pelanggan.setBorderPainted(false);
        bt_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_pelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_pelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_pelangganMouseExited(evt);
            }
        });
        bt_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pelangganActionPerformed(evt);
            }
        });

        bt_transaksi.setBackground(new java.awt.Color(255, 255, 255));
        bt_transaksi.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_transaksi.setText("Dashboard");
        bt_transaksi.setBorder(null);
        bt_transaksi.setBorderPainted(false);
        bt_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_transaksiMouseExited(evt);
            }
        });
        bt_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transaksiActionPerformed(evt);
            }
        });

        bt_barang.setBackground(new java.awt.Color(255, 255, 255));
        bt_barang.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_barang.setText("Barang");
        bt_barang.setBorder(null);
        bt_barang.setBorderPainted(false);
        bt_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_barangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_barangMouseExited(evt);
            }
        });
        bt_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_barangActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("New York");

        lb_nama.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        lb_nama.setForeground(new java.awt.Color(255, 255, 255));
        lb_nama.setText("Nama");

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        lb_hak.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        lb_hak.setForeground(new java.awt.Color(255, 255, 255));
        lb_hak.setText("hak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_petugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_barang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_transaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_pelanggan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nama)
                    .addComponent(lb_hak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nama)
                    .addComponent(logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_hak)
                .addGap(72, 72, 72)
                .addComponent(bt_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(bt_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel16)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelisi.setBackground(new java.awt.Color(255, 255, 255));

        karyawan_null.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        karyawan_null.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        karyawan_null.setText("null");

        icon_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/karyawan.png"))); // NOI18N

        pelanggan_null.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        pelanggan_null.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pelanggan_null.setText("null");

        icon_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pelanggan.png"))); // NOI18N

        barang_null.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        barang_null.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barang_null.setText("null");

        icon_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barang.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelisiLayout = new javax.swing.GroupLayout(panelisi);
        panelisi.setLayout(panelisiLayout);
        panelisiLayout.setHorizontalGroup(
            panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelisiLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelisiLayout.createSequentialGroup()
                        .addGroup(panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelisiLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(icon_barang)
                                .addGap(74, 74, 74)
                                .addComponent(icon_pelanggan)
                                .addGap(74, 74, 74)
                                .addComponent(icon_karyawan))
                            .addGroup(panelisiLayout.createSequentialGroup()
                                .addComponent(barang_null, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(pelanggan_null, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(karyawan_null, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelisiLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        panelisiLayout.setVerticalGroup(
            panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addGroup(panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_barang)
                    .addComponent(icon_pelanggan)
                    .addGroup(panelisiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(icon_karyawan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(karyawan_null)
                    .addComponent(pelanggan_null)
                    .addComponent(barang_null))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        lb_date.setBackground(new java.awt.Color(0, 255, 204));
        lb_date.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        lb_date.setForeground(new java.awt.Color(255, 255, 255));
        lb_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_date.setText("07 February 2020 ");

        lb_time.setBackground(new java.awt.Color(0, 255, 204));
        lb_time.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        lb_time.setForeground(new java.awt.Color(255, 255, 255));
        lb_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_time.setText("07.50.00 PM");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lb_date, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(302, 302, 302)
                .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_time)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transaksiActionPerformed
        tampil();
        try {
            panelisi.removeAll();
            
            Frame.dashboard.setVisible(true);
            
            panelisi.add(Frame.dashboard);
            Frame.dashboard.setMaximum(true);
            Frame.dashboard.setBorder(null);
            ((BasicInternalFrameUI) Frame.dashboard.getUI()).setNorthPane(null);
            panelisi.repaint();
        } catch (PropertyVetoException ex) {
            System.out.print("error"+ex);
        }
    }//GEN-LAST:event_bt_transaksiActionPerformed

    private void bt_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transaksiMouseExited
        bt_transaksi.setBackground(e);
        bt_transaksi.setForeground(f);
    }//GEN-LAST:event_bt_transaksiMouseExited

    private void bt_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transaksiMouseEntered
        bt_transaksi.setBackground(d);
        bt_transaksi.setForeground(e);
    }//GEN-LAST:event_bt_transaksiMouseEntered

    private void bt_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pelangganActionPerformed

    private void bt_pelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pelangganMouseExited
        bt_pelanggan.setBackground(e);
        bt_pelanggan.setForeground(f);
    }//GEN-LAST:event_bt_pelangganMouseExited

    private void bt_pelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pelangganMouseEntered
        bt_pelanggan.setBackground(d);
        bt_pelanggan.setForeground(e);
    }//GEN-LAST:event_bt_pelangganMouseEntered

    private void bt_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pelangganMouseClicked
        
        try {
            panelisi.removeAll();
            
            Frame.pelanggan.setVisible(true);
            
            panelisi.add(Frame.pelanggan);
            Frame.pelanggan.setMaximum(true);
            Frame.pelanggan.setBorder(null);
            ((BasicInternalFrameUI) Frame.pelanggan.getUI()).setNorthPane(null);
            panelisi.repaint();
        } catch (PropertyVetoException ex) {
            System.out.print("error"+ex);
        }
    }//GEN-LAST:event_bt_pelangganMouseClicked

    private void bt_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_barangActionPerformed
        try {
            panelisi.removeAll();
            
            Frame.barang.setVisible(true);
            
            panelisi.add(Frame.barang);
            Frame.barang.setMaximum(true);
            Frame.barang.setBorder(null);
            ((BasicInternalFrameUI) Frame.barang.getUI()).setNorthPane(null);
            panelisi.repaint();
        } catch (PropertyVetoException ex) {
            System.out.print("error"+ex);
        }
    }//GEN-LAST:event_bt_barangActionPerformed

    private void bt_barangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_barangMouseExited
        bt_barang.setBackground(e);
        bt_barang.setForeground(f);
    }//GEN-LAST:event_bt_barangMouseExited

    private void bt_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_barangMouseEntered
        bt_barang.setBackground(d);
        bt_barang.setForeground(e);
    }//GEN-LAST:event_bt_barangMouseEntered

    private void bt_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_petugasActionPerformed
        
    }//GEN-LAST:event_bt_petugasActionPerformed

    private void bt_petugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_petugasMouseExited
        bt_petugas.setBackground(e);
        bt_petugas.setForeground(f);
    }//GEN-LAST:event_bt_petugasMouseExited

    private void bt_petugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_petugasMouseEntered
        bt_petugas.setBackground(d);
        bt_petugas.setForeground(e);
    }//GEN-LAST:event_bt_petugasMouseEntered

    private void bt_petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_petugasMouseClicked
          
        try {
            panelisi.removeAll();
            
            Frame.admin.setVisible(true);
            
            panelisi.add(Frame.admin);
            Frame.admin.setMaximum(true);
            Frame.admin.setBorder(null);
            ((BasicInternalFrameUI) Frame.admin.getUI()).setNorthPane(null);
            panelisi.repaint();
        } catch (PropertyVetoException ex) {
            System.out.print("error"+ex);
        }
    }//GEN-LAST:event_bt_petugasMouseClicked

    private void bt_petugas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_petugas1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_petugas1MouseClicked

    private void bt_petugas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_petugas1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_petugas1MouseEntered

    private void bt_petugas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_petugas1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_petugas1MouseExited

    private void bt_petugas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_petugas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_petugas1ActionPerformed

    private void bt_pelanggan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pelanggan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pelanggan1MouseClicked

    private void bt_pelanggan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pelanggan1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pelanggan1MouseEntered

    private void bt_pelanggan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pelanggan1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pelanggan1MouseExited

    private void bt_pelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pelanggan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pelanggan1ActionPerformed

    private void bt_transaksi1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transaksi1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_transaksi1MouseEntered

    private void bt_transaksi1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transaksi1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_transaksi1MouseExited

    private void bt_transaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transaksi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_transaksi1ActionPerformed

    private void bt_barang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_barang1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_barang1MouseEntered

    private void bt_barang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_barang1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_barang1MouseExited

    private void bt_barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_barang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_barang1ActionPerformed

    private void bt_laporan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_laporan1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_laporan1MouseEntered

    private void bt_laporan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_laporan1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_laporan1MouseExited

    private void bt_laporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_laporan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_laporan1ActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Anda Yakin Untuk Keluar Akun ? "+nama+"", "info", JOptionPane.YES_NO_OPTION);
        if(a == JOptionPane.YES_OPTION){
            
            this.dispose();
            new login().setVisible(true);
        }
        
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(d);
        logout.setForeground(e);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
         logout.setBackground(e);
        logout.setForeground(f);
    }//GEN-LAST:event_logoutMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tampil();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    void tampil(){
        k.query = "Select count(Kode_Barang) as barang from barang";
        k.getData();
        try {
            while(k.rs.next()){
                barang_null.setText(k.rs.getString("barang"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        k.query = "Select count(Kode_Pelanggan) as pelanggan from pelanggan";
        k.getData();
        try {
            while(k.rs.next()){
                pelanggan_null.setText(k.rs.getString("pelanggan"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        k.query = "Select count(Kode_Karyawan) as karyawan from karyawan where left(Kode_Karyawan, 2) = 'PG'";
        k.getData();
        try {
            while(k.rs.next()){
                karyawan_null.setText(k.rs.getString("karyawan"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    void setDateTime(){
        Thread thread;
        thread = new Thread(){           
            public void run(){
                for(;;){
                    Calendar calendar = new GregorianCalendar();
                    hari = calendar.get(Calendar.DAY_OF_MONTH);
                    bulan = calendar.get(Calendar.MONTH);
                    
                    if(bulan == 0){
                        strBulan = "Januari";
                    }else if(bulan == 1){
                        strBulan = "Februari";
                    }else if(bulan == 2){
                        strBulan = "Maret";                        
                    }else if(bulan == 3){
                        strBulan = "April";
                    }else if(bulan == 4){
                        strBulan = "Mei";
                    }else if(bulan == 5){
                        strBulan = "Juni";                        
                    }else if(bulan == 6){
                        strBulan = "Juli";
                    }else if(bulan == 7){
                        strBulan = "Agustus";
                    }else if(bulan == 8){
                        strBulan = "September";
                    }else if(bulan == 9){
                        strBulan = "Oktober";
                    }else if(bulan == 10){
                        strBulan = "November";                        
                    }else if(bulan == 11){
                        strBulan = "Desember";
                    }
                    lb_nama.setText(nama);
                    lb_hak.setText(hak3); 
                    tahun = calendar.get(Calendar.YEAR);
                    lb_date.setText(hari + " " + strBulan + " " + tahun);
                    
                    int jam = calendar.get(Calendar.HOUR);
                    int menit = calendar.get(Calendar.MINUTE);
                    int detik = calendar.get(Calendar.SECOND);
                    int AM_PM = calendar.get(Calendar.AM_PM);
                    
                    String day = "";
                    if(AM_PM == 1){
                        day = "PM";
                    }else{
                        day = "AM";
                    }
                    String time = jam+"."+menit+"."+detik+"."+" "+day;
                    lb_time.setText(time);    
                    
                    try{
                        sleep(1000);
                    }catch(InterruptedException ex){
                        System.err.println("Error" + ex);
                    }
                }
            }
        };
        thread.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barang_null;
    private javax.swing.JLabel barang_null1;
    private javax.swing.JButton bt_barang;
    private javax.swing.JButton bt_barang1;
    private javax.swing.JButton bt_laporan1;
    private javax.swing.JButton bt_pelanggan;
    private javax.swing.JButton bt_pelanggan1;
    private javax.swing.JButton bt_petugas;
    private javax.swing.JButton bt_petugas1;
    private javax.swing.JButton bt_transaksi;
    private javax.swing.JButton bt_transaksi1;
    private javax.swing.JLabel icon_barang;
    private javax.swing.JLabel icon_barang1;
    private javax.swing.JLabel icon_karyawan;
    private javax.swing.JLabel icon_karyawan1;
    private javax.swing.JLabel icon_pelanggan;
    private javax.swing.JLabel icon_pelanggan1;
    private javax.swing.JLabel icon_transaksi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel karyawan_null;
    private javax.swing.JLabel karyawan_null1;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_date1;
    private javax.swing.JLabel lb_hak;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_time;
    private javax.swing.JLabel lb_time1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel panelisi;
    private javax.swing.JPanel panelisi1;
    private javax.swing.JLabel pelanggan_null;
    private javax.swing.JLabel pelanggan_null1;
    private javax.swing.JLabel transaksi_null1;
    // End of variables declaration//GEN-END:variables
}
