/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrasi;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Barang extends javax.swing.JInternalFrame {
    
    KoneksiDB  k = new KoneksiDB();
    DefaultTableModel tabmodel;
    String  w,x,y,z,zx,search,f,g,h,i,j,a,path,b,ambilgambar2;
    int bes;
    JFileChooser ambilgambar;
    BufferedImage gambar;
    File selectedFile;
    Blob blob;
    public String kodeBarang;
    public byte[] data ;
    ImageIcon icon; 
    Path copy,files;
    
    public Barang() {
        initComponents();
        setCode();
        showdata();
    }
    void setCode()
    {
        try {
            k.query = "select MAX(right(Kode_Barang, 2)) as no from barang";
            k.getData();
            //cek untuk record kode awal di table pelanggan
            while(k.rs.next()){
                if(k.rs.first() == false){
                tfkode.setText("B01");
            }else{
                //cek untuk record paling akhir di tbpelanggan
                k.rs.last();
                //digit terakhir dari ode pelanggan ditambah 1
                int id = k.rs.getInt(1) + 1;
                
                String no = String.valueOf(id);
                
                //cek berapa jumlah 0 yang berada pada kode pelanggan
                
                for(int i =0; i<1; i++){
                    no = "0" + no;
                }
                tfkode.setText("B"+no);
            }
            }
            
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfjual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        foto = new javax.swing.JPanel();
        foto2 = new javax.swing.JLabel();
        tfbeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcari = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_refresh = new javax.swing.JButton();
        bt_simpan = new javax.swing.JButton();
        update = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        tfStok = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        tfnama.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nma Barang");

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Barang");

        tfkode.setEditable(false);
        tfkode.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga Jual");

        tfjual.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Beli");

        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barang2.png"))); // NOI18N

        javax.swing.GroupLayout fotoLayout = new javax.swing.GroupLayout(foto);
        foto.setLayout(fotoLayout);
        fotoLayout.setHorizontalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        fotoLayout.setVerticalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tfbeli.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jLabel5.setText("Cari Data Barang  :");

        tfcari.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        tfcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcariActionPerformed(evt);
            }
        });

        tabel_barang.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga Jual", "Harga Beli", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_barang);

        jPanel3.setBackground(new java.awt.Color(231, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        bt_refresh.setBackground(new java.awt.Color(255, 255, 255));
        bt_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        bt_refresh.setText("Refresh");
        bt_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_refreshMouseEntered(evt);
            }
        });

        bt_simpan.setBackground(new java.awt.Color(255, 255, 255));
        bt_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simpan.png"))); // NOI18N
        bt_simpan.setText("Simpan");
        bt_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_simpanMouseClicked(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ubah.png"))); // NOI18N
        update.setText("Ubah");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(255, 255, 255));
        bt_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hapus.png"))); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Montserrat", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Supreme");

        jLabel7.setFont(new java.awt.Font("Montserrat", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data Barang");

        browse.setText("BROWSE");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stok");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfkode, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(tfnama))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(tfjual, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(bt_simpan)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(update)
                                .addGap(33, 33, 33)
                                .addComponent(bt_hapus)))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_refresh)
                        .addComponent(bt_simpan)
                        .addComponent(update)
                        .addComponent(bt_hapus)))
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcariActionPerformed
        
      try {
            tabmodel = (DefaultTableModel) tabel_barang.getModel();
            tabmodel.getDataVector().removeAllElements();
            revalidate();
            search = tfcari.getText();
            
            k.query = "select b.Kode_Barang, b.Nama_Barang, b.Harga_Jual, b.Harga_Beli, db.Stok from barang b, detail_barang db where b.Kode_Barang = db.Kode_Barang AND b.Nama_Barang like '%"+search+"%' or b.Kode_Barang = db.Kode_Barang AND b.Kode_Barang LIKE '%"
                    +search+"%' or b.Kode_Barang = db.Kode_Barang AND b.Harga_Jual like '%"+search+"%' or b.Kode_Barang = db.Kode_Barang AND b.Harga_Beli like '%"
                    +search+"%' or b.Kode_Barang = db.Kode_Barang AND db.Stok like '%"+search+"%'"; 
           
            k.getData();
            while(k.rs.next()){
                //menampilkan database ke frame
                f = k.rs.getString("Kode_Barang");
                g = k.rs.getString("Nama_Barang");
                h = k.rs.getString("Harga_Jual");
                i = k.rs.getString("Harga_Beli");
                j = k.rs.getString("Stok");
           
                String[] data = {f,g,h,i,j};
                tabmodel.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tfcariActionPerformed

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        tabmodel = (DefaultTableModel) tabel_barang.getModel();
        int pilih = tabel_barang.rowAtPoint(evt.getPoint());
        kodeBarang = (String)tabel_barang.getValueAt(pilih, 0);
        tfkode.setText(kodeBarang);
        tfnama.setText((String)tabel_barang.getValueAt(pilih, 1));
        tfjual.setText(tabmodel.getValueAt(pilih, 2).toString());
        tfbeli.setText(tabmodel.getValueAt(pilih, 3).toString());
        tfStok.setText(tabmodel.getValueAt(pilih, 4).toString());
        
        k.query = "select Gambar from barang where Kode_Barang = '"+kodeBarang+"'"; 
        k.getData();
        try {
            while(k.rs.next()){
                //menampilkan database ke frame
                
                ambilgambar2 = k.rs.getString("Gambar");
                File dir = new File(System.getProperty("user.dir"));
                String ubah = String.valueOf(dir);
                
                String alamat=ubah+"/src/images/barang/"+ambilgambar2+"";
                try {
                    gambar = ImageIO.read(new File(alamat));
                } catch (IOException ex) {
                    Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
                }
                foto2.setIcon(new ImageIcon(gambar.getScaledInstance(foto2.getWidth(), foto2.getHeight(), Image.SCALE_SMOOTH)));
           
            }   
        } catch (SQLException ex) {
            System.out.print(ex);
        }
        
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void bt_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refreshMouseClicked
        setCode();
        showdata();
        bersih();
    }//GEN-LAST:event_bt_refreshMouseClicked

    private void bt_refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refreshMouseEntered

    }//GEN-LAST:event_bt_refreshMouseEntered

    private void bt_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_simpanMouseClicked

        if(tfnama.getText().equals("") || tfbeli.getText().equals("") || tfjual.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Lengkapi Data", "info",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                k.query = "Insert into barang value (?,?,?,?,?)";
                k.setData();
                k.ps.setString(1, tfkode.getText());
                k.ps.setString(2, tfnama.getText());
                k.ps.setString(3, tfbeli.getText());
                k.ps.setString(4, tfjual.getText());
                
//                try {
//                    k.ps.setBlob(5, new FileInputStream(selectedFile));
//                } catch (FileNotFoundException ex) {
//                    Logger.getLogger(ubahPegawai.class.getName()).log(Level.SEVERE, null, ex);
//                }
                try {
                    
                    
                    File dir = new File(System.getProperty("user.dir"));
                    copy = Paths.get(dir+"/src/images/barang/"+b);
                    CopyOption[] options = new CopyOption[]{
                            StandardCopyOption.REPLACE_EXISTING,
                            StandardCopyOption.COPY_ATTRIBUTES,
                    };
                    Files.copy(files, copy,options);
                } catch (IOException ex) {
                    System.out.print("Error"+ex);
                }
                k.ps.setString(5, b);
                k.ps.executeUpdate();
                
                k.query = "Insert into detail_barang value (?,?)";
                k.setData();
                k.ps.setString(1, tfkode.getText());
                k.ps.setString(2, tfStok.getText());
                
                k.ps.executeUpdate();
                
                bersih();
                setCode();
                
                showdata();
            } catch (SQLException ex) {
                System.out.print("Error"+ex);
            }
            
            showdata();
        }

    }//GEN-LAST:event_bt_simpanMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        if(tfnama.getText().equals("")|| tfjual.getText().equals("") || tfbeli.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Yang di Ubah", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                k.query = "UPDATE barang SET Nama_Barang = ?, Harga_Jual = ?, Harga_Beli = ?, Gambar=? WHERE Kode_Barang = '"+tfkode.getText()+"'";
                k.setData();
                
                k.ps.setString(1, tfnama.getText());
                k.ps.setString(2, tfjual.getText());
                k.ps.setString(3, tfbeli.getText());                
                
                if(bes == 1 ){
                    try {
                    File dir = new File(System.getProperty("user.dir"));
                    
                    File alamat= new File(dir+"/src/images/barang/"+ambilgambar2+"");
                    alamat.delete();
                    
                    copy = Paths.get(dir+"/src/images/barang/"+b);
                    CopyOption[] options = new CopyOption[]{
                            StandardCopyOption.REPLACE_EXISTING,
                            StandardCopyOption.COPY_ATTRIBUTES,
                    };
                    Files.copy(files, copy,options);
                    } catch (IOException ex) {
                        System.out.print("Error"+ex);
                    }    
                    k.ps.setString(4, b);
                }
                else{
                    k.ps.setString(4, ambilgambar2);
                }
                
                k.ps.executeUpdate();
                
                k.query = "UPDATE detail_barang SET Stok = ? WHERE Kode_Barang = '"+tfkode.getText()+"'";
                k.setData();
                k.ps.setString(1, tfStok.getText());
                k.ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Sudah Di update", "info",JOptionPane.INFORMATION_MESSAGE);
                bersih();
                showdata();
                setCode();
            } catch (SQLException ex) {
                System.out.println("Error" + ex);
            }
            
        } 
    }//GEN-LAST:event_updateMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void bt_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusMouseClicked
        tabmodel = (DefaultTableModel) tabel_barang.getModel();
        int a = JOptionPane.showConfirmDialog(null, "yakin ingin menghapus data "
                    +tfnama.getText()+" ?", "Warning", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                try {
                    
                    k.query = "delete from detail_barang where Kode_Barang ='"+tfkode.getText()+"'";
                    k.setData();
                    k.ps.executeUpdate();
                    
                    k.query = "delete from barang where Kode_Barang ='"+tfkode.getText()+"'";
                    k.setData();
                    k.ps.executeUpdate();
                    
                    
                    setCode();
                    showdata();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus","info",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    System.out.println("error");
                }
                bersih();
            } 

    }//GEN-LAST:event_bt_hapusMouseClicked

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
       bes = 0;
        ambilgambar = new JFileChooser();
        ambilgambar.setFileFilter(new FileNameExtensionFilter("All Files Images", "JPG","PNG","JPEG","BMP"));
        ambilgambar.setAcceptAllFileFilterUsed(true);

        int setuju = ambilgambar.showSaveDialog(null);
        if(setuju == JFileChooser.APPROVE_OPTION){
            try {
                selectedFile = ambilgambar.getSelectedFile();
                path = selectedFile.getAbsolutePath();
                b = selectedFile.getName();
                gambar = ImageIO.read(new File(path));
                foto2.setIcon(new ImageIcon(gambar.getScaledInstance(foto2.getWidth(), foto2.getHeight(), Image.SCALE_SMOOTH)));
                a = path;
                files = Paths.get(selectedFile.toURI());
                bes =1;
            } catch (IOException ex) {
                System.out.println("Error"+ ex);
            }

        }
    }//GEN-LAST:event_browseActionPerformed
    
    void bersih(){
        tfnama.setText("");
        tfjual.setText("");
        tfbeli.setText("");
        tfStok.setText("");
        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barang2.png")));
    }
    void showdata(){
        tabmodel = (DefaultTableModel) tabel_barang.getModel();
        tabmodel.getDataVector().removeAllElements();
        revalidate();
        k.query = "select b.Kode_Barang, b.Nama_Barang, b.Harga_Jual, b.Harga_Beli, db.stok from barang b, detail_barang db where b.Kode_Barang = db.Kode_Barang"; 
        k.getData();
        try {
            while(k.rs.next()){
                //menampilkan database ke frame
                w = k.rs.getString("Kode_Barang");
                x = k.rs.getString("Nama_Barang");
                y = k.rs.getString("Harga_Jual");
                z = k.rs.getString("Harga_Beli");
                zx = k.rs.getString("Stok");
                String[] data = {w,x,y,z,zx};
                tabmodel.addRow(data);
            }   } catch (SQLException ex) {
            System.out.print(ex);
    }   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JPanel foto;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTextField tfStok;
    private javax.swing.JTextField tfbeli;
    private javax.swing.JTextField tfcari;
    private javax.swing.JTextField tfjual;
    private javax.swing.JTextField tfkode;
    private javax.swing.JTextField tfnama;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
