/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrasi;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.table.DefaultTableModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author RPL
 */
public class pegawai extends javax.swing.JFrame {

    KoneksiDB k = new KoneksiDB();
    String tgl,a,b;
    int bes;
    JFileChooser ambilgambar;
    BufferedImage gambar;
    File selectedFile;
    String path;
    Path files,copy;
    
    public pegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJenkel = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        bt_browse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbPria = new javax.swing.JRadioButton();
        rbWanita = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        cbhak = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        bt_simpan = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(231, 0, 0));

        jLabel1.setFont(new java.awt.Font("Montserrat", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Supreme");

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/karyawan2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bt_browse.setBackground(new java.awt.Color(153, 153, 153));
        bt_browse.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_browse.setForeground(new java.awt.Color(255, 255, 255));
        bt_browse.setText("BROWSE");
        bt_browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_browseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE PEGAWAI");

        tfkode.setEditable(false);
        tfkode.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        tfkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkodeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA PEGAWAI");

        tfNama.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JENIS KELAMIN");

        rbPria.setBackground(new java.awt.Color(231, 0, 0));
        bgJenkel.add(rbPria);
        rbPria.setForeground(new java.awt.Color(255, 255, 255));
        rbPria.setText("Pria");

        rbWanita.setBackground(new java.awt.Color(231, 0, 0));
        bgJenkel.add(rbWanita);
        rbWanita.setForeground(new java.awt.Color(255, 255, 255));
        rbWanita.setText("Wanita");
        rbWanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWanitaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ALAMAT");

        taAlamat.setColumns(20);
        taAlamat.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NO. HANDPHONE");

        tfNo.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USERNAME");

        tfUser.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PASSWORD");

        tfPassword.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HAK AKSES");

        cbhak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==PILIH==", "Admin", "Pemilik Toko", "Karyawan" }));
        cbhak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhakActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        exit.setText("KELUAR");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        bt_simpan.setBackground(new java.awt.Color(255, 255, 255));
        bt_simpan.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        bt_simpan.setText("SIMPAN");
        bt_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_simpanMouseClicked(evt);
            }
        });

        btClear.setBackground(new java.awt.Color(255, 255, 255));
        btClear.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btClear.setText("CLEAR");
        btClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btClear)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(bt_simpan)
                    .addComponent(btClear))
                .addGap(16, 16, 16))
        );

        jLabel3.setFont(new java.awt.Font("Montserrat", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNo)
                            .addComponent(tfUser)
                            .addComponent(tfPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNama)
                                    .addComponent(tfkode)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbPria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbWanita)
                                        .addGap(0, 248, Short.MAX_VALUE))
                                    .addComponent(cbhak, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbhak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPria)
                            .addComponent(jLabel5)
                            .addComponent(rbWanita))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbhakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhakActionPerformed
        if(cbhak.getSelectedItem() == "==PILIH=="){
            JOptionPane.showMessageDialog(null, "Tentukan Hak Aksesnya", "info", JOptionPane.INFORMATION_MESSAGE);

        }
        else if(cbhak.getSelectedItem() == "Admin"){
            try {
                k.query = "select MAX(right(Kode_Karyawan, 2)) as no from karyawan where left(Kode_Karyawan, 3) = 'ADM'";
                k.getData();
                while (k.rs.next()){
                    if (k.rs.first() == false){
                        tfkode.setText("ADM01");
                    }
                    else{
                        k.rs.last();
                        int id=k.rs.getInt(1) + 1;
                        String no = String.valueOf(id);

                        for(int i =0; i<1; i++){
                            no = "0" + no;
                        }
                        tfkode.setText("ADM"+no);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(pegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(cbhak.getSelectedItem() == "Pemilik Toko"){
            try {
                k.query = "select MAX(right(Kode_Karyawan, 2)) as no from karyawan where left(Kode_Karyawan, 2) = 'PT'";
                k.getData();
                while (k.rs.next()){
                    if (k.rs.first() == false){
                        tfkode.setText("PT01");
                    }
                    else{
                        k.rs.last();
                        int id=k.rs.getInt(1) + 1;
                        String no = String.valueOf(id);

                        for(int i =0; i<1; i++){
                            no = "0" + no;
                        }
                        tfkode.setText("PT"+no);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(pegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(cbhak.getSelectedItem() == "Karyawan"){
            try {
                k.query = "select MAX(right(Kode_Karyawan, 2)) as no from karyawan where left(Kode_Karyawan, 2) = 'PG'";
                k.getData();
                while (k.rs.next()){
                    if (k.rs.first() == false){
                        tfkode.setText("PG01");
                    }
                    else{
                        k.rs.last();
                        int id=k.rs.getInt(1) + 1;
                        String no = String.valueOf(id);

                        for(int i =0; i<1; i++){
                            no = "0" + no;
                        }
                        tfkode.setText("PG"+no);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(pegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbhakActionPerformed

    private void rbWanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWanitaActionPerformed

    private void bt_browseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_browseMouseClicked
        ambilgambar = new JFileChooser();
        ambilgambar.setFileFilter(new FileNameExtensionFilter("All Files Images", "JPG","PNG","JPEG","BMP"));
        ambilgambar.setAcceptAllFileFilterUsed(true);
        bes = 0;
        int setuju = ambilgambar.showSaveDialog(null);
        if(setuju == JFileChooser.APPROVE_OPTION){
            try {
                
                selectedFile = ambilgambar.getSelectedFile();
                path = selectedFile.getAbsolutePath();
                b = selectedFile.getName();
                gambar = ImageIO.read(new File(path));
                foto.setIcon(new ImageIcon(gambar.getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_SMOOTH)));
                a = path;
                files = Paths.get(selectedFile.toURI());
                bes =1;
                
                
            } catch (IOException ex) {
                System.out.println("Error"+ ex);
            }

        }
    }//GEN-LAST:event_bt_browseMouseClicked

    private void bt_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_simpanMouseClicked
         if(tfkode.getText().equals("") || taAlamat.getText().equals("") || tfNo.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Lengkapi Data", "info",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                if(cbhak.getSelectedItem() == "Pemilik Toko"){
                    k.query = "Insert into p_toko value (?,?)";
                    k.setData();
                    k.ps.setString(1, tfkode.getText());
                    k.ps.setString(2, tfNama.getText());
                    k.ps.executeUpdate();
                }
                
                    k.query = "Insert into Karyawan value (?,?,?,?,?,?)";
                    k.setData();
                    k.ps.setString(1, tfkode.getText());
                    k.ps.setString(2, tfNama.getText());
                    k.ps.setString(3, taAlamat.getText());
                    if(rbPria.isSelected()){
                        k.ps.setString(4, rbPria.getText()); 
                    }
                    else if(rbWanita.isSelected()){
                        k.ps.setString(4, rbWanita.getText()); 
                    }
                    k.ps.setString(5, tfNo.getText());
                    try {
                    
                    
                    File dir = new File(System.getProperty("user.dir"));
                    copy = Paths.get(dir+"/src/images/karyawan/"+b);
                    CopyOption[] options = new CopyOption[]{
                            StandardCopyOption.REPLACE_EXISTING,
                            StandardCopyOption.COPY_ATTRIBUTES,
                    };
                    Files.copy(files, copy,options);
                    } catch (IOException ex) {
                        System.out.print("Error"+ex);
                    }
                    k.ps.setString(6, b);
                    k.ps.executeUpdate();
                
                
                
                k.query = "Insert into login value (?,?,?,?)";
                k.setData();
                k.ps.setString(1, tfkode.getText());
                k.ps.setString(2, tfUser.getText());
                k.ps.setString(3, tfPassword.getText());
                k.ps.setString(4, cbhak.getSelectedItem().toString());
                k.ps.executeUpdate();
                
               JOptionPane.showMessageDialog(null,"Data Sudah Dimasukan", "info",JOptionPane.INFORMATION_MESSAGE); 
                
            } catch (SQLException ex) {
                System.out.print("Error"+ex);
            }
            
            
        }
    }//GEN-LAST:event_bt_simpanMouseClicked

    private void tfkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkodeActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed
            
    private void btClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClearMouseClicked
        cbhak.setSelectedItem(null);
        tfkode.setText("");
        tfNama.setText("");
        bgJenkel.clearSelection();
        taAlamat.setText("");
        tfNo.setText("");
        tfUser.setText("");
        tfPassword.setText("");
        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/karyawan2.png")));
    }//GEN-LAST:event_btClearMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
      
            
            
            Frame.admin.setVisible(true);
            this.setVisible(false);
            
      
    }//GEN-LAST:event_exitMouseClicked
    
  
    
    
                
                
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJenkel;
    private javax.swing.JButton btClear;
    private javax.swing.JButton bt_browse;
    private javax.swing.JButton bt_simpan;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbhak;
    private javax.swing.JButton exit;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbPria;
    private javax.swing.JRadioButton rbWanita;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNo;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUser;
    private javax.swing.JTextField tfkode;
    // End of variables declaration//GEN-END:variables
}
