        /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrasi;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RPL
 */
public class Pelanggan extends javax.swing.JInternalFrame {
    
    KoneksiDB  k = new KoneksiDB();
    DefaultTableModel tabmodel;
    Color d=new Color(0,153,153);
    Color e=new Color(255,0,153);
    String  w,x,y,z,search,f,g,h,i;
    
    public Pelanggan() {
        initComponents();
        setCode();
        showdata();
    }
    void setCode()
    {
        try {
            k.query = "select MAX(right(Kode_Pelanggan, 2)) as no from Pelanggan";
            k.getData();
            //cek untuk record kode awal di table pelanggan
            while(k.rs.next()){
                if(k.rs.first() == false){
                tfkode.setText("P01");
            }else{
                //cek untuk record paling akhir di tbpelanggan
                k.rs.last();
                //digit terakhir dari ode pelanggan ditambah 1
                int id = k.rs.getInt(1) + 1;
                
                String no = String.valueOf(id);
                
                //cek berapa jumlah 0 yang berada pada kode pelanggan
                
                for(int i =0; i<1; i++){
                    no = "0" + no;
                }
                tfkode.setText("P"+no);
            }
            }
            
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfalamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tfno = new javax.swing.JTextField();
        bt_refresh = new javax.swing.JButton();
        bt_simpan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_pelanggan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfcari = new javax.swing.JTextField();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jPanel4.setBackground(new java.awt.Color(255, 102, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Pelanggan :");

        tfkode.setEditable(false);
        tfkode.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nma Pelanggan :");

        tfnama.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat :");

        tfalamat.setColumns(20);
        tfalamat.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        tfalamat.setRows(5);
        jScrollPane1.setViewportView(tfalamat);

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No.Handphone :");

        tfno.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        tfno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnoKeyTyped(evt);
            }
        });

        bt_refresh.setBackground(new java.awt.Color(255, 255, 255));
        bt_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        bt_refresh.setText("Refresh");
        bt_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_refreshMouseEntered(evt);
            }
        });

        bt_simpan.setBackground(new java.awt.Color(255, 255, 255));
        bt_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simpan.png"))); // NOI18N
        bt_simpan.setText("Simpan");
        bt_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_simpanMouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ubah.png"))); // NOI18N
        jButton3.setText("Ubah");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(255, 255, 255));
        bt_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hapus.png"))); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(231, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(390, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        tabel_pelanggan.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        tabel_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pelanggan", "Nama Pelanggan", "Alamat", "No Handphone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_pelanggan);

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jLabel5.setText("Cari Data Pelanggan  :");

        tfcari.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        tfcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_refresh)
                        .addGap(18, 18, 18)
                        .addComponent(bt_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hapus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfnama)
                                    .addComponent(jScrollPane1)
                                    .addComponent(tfkode, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfno)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfcari))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_refresh)
                    .addComponent(bt_simpan)
                    .addComponent(jButton3)
                    .addComponent(bt_hapus))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt_refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refreshMouseEntered
  
    }//GEN-LAST:event_bt_refreshMouseEntered

    private void bt_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_simpanMouseClicked
        
        if(tfnama.getText().equals("") || tfalamat.getText().equals("") || tfno.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Lengkapi Data", "info",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                k.query = "Insert into Pelanggan value (?,?,?,?)";
                k.setData();
                k.ps.setString(1, tfkode.getText());
                k.ps.setString(2, tfnama.getText());
                k.ps.setString(3, tfalamat.getText());
                k.ps.setString(4, tfno.getText());
                k.ps.executeUpdate();
                bersih();
                setCode();
                
                showdata();
            } catch (SQLException ex) {
                System.out.print("Error"+ex);
            }
            
            showdata();
        }
        
            
    }//GEN-LAST:event_bt_simpanMouseClicked

    private void tabel_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pelangganMouseClicked
        tabmodel = (DefaultTableModel) tabel_pelanggan.getModel();
        int pilih = tabel_pelanggan.rowAtPoint(evt.getPoint());
        tfkode.setText((String)tabel_pelanggan.getValueAt(pilih, 0));
        tfnama.setText((String)tabel_pelanggan.getValueAt(pilih, 1));
        tfalamat.setText(tabmodel.getValueAt(pilih, 2).toString());
        tfno.setText(tabmodel.getValueAt(pilih, 3).toString());
    }//GEN-LAST:event_tabel_pelangganMouseClicked

    private void bt_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refreshMouseClicked
        showdata();
        bersih();
    }//GEN-LAST:event_bt_refreshMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
         if(tfnama.getText().equals("")|| tfno.getText().equals("") || tfalamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Yang di Ubah", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                k.query = "UPDATE Pelanggan SET Nama_Pelanggan = ?, Alamat = ?, No_HP = ? WHERE Kode_Pelanggan = '"+tfkode.getText()+"'";
                k.setData();
                
                k.ps.setString(1, tfnama.getText());
                k.ps.setString(2, tfalamat.getText());
                k.ps.setString(3, tfno.getText());                
                
                k.ps.executeUpdate();                
                bersih();
                showdata();
                setCode();
            } catch (SQLException ex) {
                System.out.println("Error" + ex);
            }
            
        } 
    }//GEN-LAST:event_jButton3MouseClicked

    private void bt_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusMouseClicked
        tabmodel = (DefaultTableModel) tabel_pelanggan.getModel();
        int a = JOptionPane.showConfirmDialog(null, "yakin ingin menghapus data "
                    +tfnama.getText()+" ?", "Warning", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                try {
                    
                    k.query = "delete from Pelanggan where Kode_Pelanggan ='"+tfkode.getText()+"'";
                    k.setData();
                    k.ps.executeUpdate();
                    setCode();
                    showdata();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus","info",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    System.out.println("error");
                }
                bersih();
            } 
            
    }//GEN-LAST:event_bt_hapusMouseClicked

    private void tfcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcariActionPerformed

        try {
            tabmodel = (DefaultTableModel) tabel_pelanggan.getModel();
            tabmodel.getDataVector().removeAllElements();
            revalidate();
            search = tfcari.getText();
            
            k.query = "select * from Pelanggan where Nama_Pelanggan like '%"+search+"%' or Kode_Pelanggan LIKE '%"
                    +search+"%' or Alamat like '%"+search+"%' or No_HP like '%"
                    +search+"%'"; 
           
            k.getData();
            while(k.rs.next()){
                //menampilkan database ke frame
                f = k.rs.getString("Kode_Pelanggan");
                g = k.rs.getString("Nama_Pelanggan");
                h = k.rs.getString("Alamat");
                i = k.rs.getString("No_HP");
           
                String[] data = {f,g,h,i};
                tabmodel.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_tfcariActionPerformed

    private void tfnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnoKeyTyped
        if(Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tfnoKeyTyped
    void bersih(){
        tfnama.setText("");
        tfalamat.setText("");
        tfno.setText("");
        
    }
    
    void showdata(){
        tabmodel = (DefaultTableModel) tabel_pelanggan.getModel();
        tabmodel.getDataVector().removeAllElements();
        revalidate();
        k.query = "select * from Pelanggan"; 
        k.getData();
        try {
            while(k.rs.next()){
                //menampilkan database ke frame
                w = k.rs.getString("Kode_Pelanggan");
                x = k.rs.getString("Nama_Pelanggan");
                y = k.rs.getString("Alamat");
                z = k.rs.getString("No_HP");
                String[] data = {w,x,y,z};
                tabmodel.addRow(data);
            }   } catch (SQLException ex) {
            System.out.print(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTable tabel_pelanggan;
    private javax.swing.JTextArea tfalamat;
    private javax.swing.JTextField tfcari;
    private javax.swing.JTextField tfkode;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfno;
    // End of variables declaration//GEN-END:variables
}
